window._tx=function(d){d.lib=function(b){function r(){try{var a=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(n){a=!1}}a||"undefined"==typeof XMLHttpRequest||(a=new XMLHttpRequest);return a}b.txqpid=null;b.foadh=null;b.cdh=null;b.ddh=".hybrid.ai";b.aldhs=[".adhello.pl",".rtbdro.id",".iclicks.io",".twigacg.com"];b.ppb=!1;var m=function(a){a.stringify=function(c){return window.JSON&&window.JSON.stringify?window.JSON.stringify(c):a.encode(c)};a.parse=
function(c){return window.JSON&&window.JSON.parse?window.JSON.parse(c):a.decode(c)};a.encode=function(a){switch(typeof a){case "string":return"'"+a+"'";case "number":return isFinite(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";var c=[];if("[object Array]"===Object.prototype.toString.apply(a)){for(var b=0;b<a.length;b++)c[b]=this.encode(a[b])||"null";return"["+c.join(",")+"]"}for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var f=this.encode(a[b]);
f&&c.push("'"+b+"':"+f)}return"{"+c.join(",")+"}"}};a.decode=function(a){return null!==a&&"string"===typeof a&&/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,"@").replace(/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?(new Function("return "+a))():null};return a}(d.JSON||{}),v=function(){var a={};try{location&&location.href&&4<location.href.length&&1E3>location.href.length&&(a.Url=location.href),document&&document.referrer&&
4<document.referrer.length&&1E3>document.referrer.length&&(a.Referrer=document.referrer),a.Language=navigator?navigator.language||navigator.browserLanguage:"",screen&&Number(screen.width)===screen.width&&0===screen.width%1&&Number(screen.height)===screen.height&&0===screen.height%1&&0<screen.width&&2147483647>screen.width&&0<screen.height&&2147483647>screen.height&&(a.ScreenWidth=screen.width,a.ScreenHeight=screen.height),a.TimezoneOffset=(new Date).getTimezoneOffset()/60}catch(c){}return a},w=function(a,
c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent&&a.attachEvent("on"+c,b)},y=function(a,b){var c=document.createElement("script");c.type="text/javascript";c.async=b;c.src=a;(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(c)},A=function(a){if(window.Image)var c=new Image;else document&&(c=document.createElement("img"),c.width=1,c.height=1);if(c)c.onload=c.onerror=function(){c.onload=null;c.onerror=null},c.src=a;else{var b=r();b&&(b.open("GET",
a,!0),b.send(null))}},B=function(){var a={apl:null,cs:"",pcs:[],vcs:[]},b=window.__tcfapi;if(!b)try{for(var d,e=window;e;){try{if(e.frames.__tcfapiLocator){d=e;break}}catch(g){}if(e===window.top)break;e=e.parent}if(d){var f={};b=function(a,b,c,e){var g=Math.random()+"";a={__tcfapiCall:{command:a,parameter:e,version:b,callId:g}};f[g]=c;d.postMessage(a,"*")};w(window,"message",function(a){a="string"===typeof a.data?m.parse(a.data):a.data;a.__tcfapiReturn&&(a=a.__tcfapiReturn,"function"===typeof f[a.callId]&&
(f[a.callId](a.returnValue,a.success),delete f[a.callId]))},!1)}}catch(g){}if(b)try{e=function(c,e){if(c){a.apl=a.apl||c.gdprApplies;a.cs=a.cs||c.tcString;if(c.purpose&&c.purpose.consents)for(var g in c.purpose.consents)c.purpose.consents[g]&&-1===a.pcs.indexOf(g)&&a.pcs.push(g);if(c.vendor&&c.vendor.consents)for(var d in c.vendor.consents)c.vendor.consents[d]&&-1===a.vcs.indexOf(d)&&a.vcs.push(d);try{"tcloaded"===c.eventStatus&&b("removeEventListener",2,function(a){},c.listenerId)}catch(E){}}};try{b("addEventListener",
2,e)}catch(g){}try{b("getTCData",2,e)}catch(g){}b("getTCData",1,e)}catch(g){}e=window.__cmp;if(!e)try{for(var h,k=window;!h;){try{k.frames.__cmpLocator&&(h=k)}catch(g){}if(k===window.top)break;k=k.parent}if(h){var l={};e=function(a,b,c){var g=Math.random()+"";a={__cmpCall:{command:a,parameter:b,callId:g}};l[g]=c;h.postMessage(a,"*")};w(window,"message",function(a){a="string"===typeof a.data?m.parse(a.data):a.data;a.__cmpReturn&&(a=a.__cmpReturn,l[a.callId](a.returnValue,a.success),delete l[a.callId])},
!1)}}catch(g){}if(e)try{k=function(b,c){if(b){a.apl=a.apl||b.gdprApplies;a.cs=a.cs||b.consentData||b.metadata||"";if(b.purposeConsents)for(var e in b.purposeConsents)b.purposeConsents[e]&&-1===a.pcs.indexOf(e)&&a.pcs.push(e);if(b.vendorConsents)for(var d in b.vendorConsents)b.vendorConsents[d]&&-1===a.vcs.indexOf(d)&&a.vcs.push(d)}};try{e("getConsentData",null,k)}catch(g){}e("getVendorConsents",null,k)}catch(g){}return a},p=function(a){return"foadh="+encodeURIComponent(a||"")},q=function(){var a=
B();return"gapl="+(null!=a.apl?a.apl?"1":"0":"")+"&cs="+a.cs+"&pcs="+a.pcs.join("_")+"&vcs="+a.vcs.join("_")},z=function(){var a=document.getElementsByTagName("script");if(a)for(var c=0;c<a.length;c++){var d=a[c].src;if(d)for(var e=0;e<b.aldhs.length;e++){var f=b.aldhs[e];if(-1<d.indexOf(f)&&(-1<d.indexOf("txsp.js")||-1<d.indexOf("advertiser.js")))return f}}return b.ddh},t=function(){return"https://dss"+(b.cdh||z())+"/"},u=function(a){b.ppb?window.setTimeout(function(){u(a)},1E3):(b.ppb=!0,A(a),window.setTimeout(function(){b.ppb=
!1},1E3))},x=function(a,b,d,e,f,h,k,l,g){a="Pixel/Track2?pid="+(a||"")+"&bobid="+(b||"")+"&evt="+encodeURIComponent(d||"")+"&cost="+encodeURIComponent(e||"")+"&text="+encodeURIComponent(f||"")+"&ltm="+(k||!1)+"&cnt="+(h||"")+"&url="+encodeURIComponent(l.Url||"")+"&rf="+encodeURIComponent(l.Referrer||"")+"&lng="+(l.Language||"")+"&tz="+(l.TimezoneOffset||"")+"&sw="+(l.ScreenWidth||"")+"&sh="+(l.ScreenHeight||"")+"&"+p(g)+"&"+q()+"&r=";u(t()+a)},C=function(a,b,d,e,f,h){a="Pixel/DynamicTrack?pid="+(a||
"")+"&bobid="+(b||"")+"&evt="+encodeURIComponent(d||"")+"&cnt="+encodeURIComponent(e||"")+"&url="+encodeURIComponent(f.Url||"")+"&rf="+encodeURIComponent(f.Referrer||"")+"&lng="+(f.Language||"")+"&tz="+(f.TimezoneOffset||"")+"&sw="+(f.ScreenWidth||"")+"&sh="+(f.ScreenHeight||"")+"&"+p(h)+"&"+q()+"&r=";u(t()+a)},D=function(a,b,d,e,f,h,k){a="Pixel/Identify2?pid="+(a||"")+"&bobid="+(b||"")+"&cstid="+(d||"")+"&icnt="+(e||"")+"&ucnt="+(f||"")+"&url="+encodeURIComponent(h.Url||"")+"&rf="+encodeURIComponent(h.Referrer||
"")+"&lng="+(h.Language||"")+"&tz="+(h.TimezoneOffset||"")+"&sw="+(h.ScreenWidth||"")+"&sh="+(h.ScreenHeight||"")+"&"+p(k)+"&"+q()+"&r=";u(t()+a)};b.txqhnd=function(a){if(a&&"string"===typeof a[0]){var c=a[0].toLowerCase();if("createpixel"===c)"string"==typeof a[1]&&(b.txqpid=a[1],a[2]&&(b.foadh=1),window.setTimeout(function(){var a=p(b.foadh),c=q();y("https://emd.hybrid.ai/plgt.js?fbpid="+b.txqpid+"&"+a+"&"+c,!0)},2E3));else if("track"===c){if("string"===typeof a[1]){var n=a[1],e=null;try{a[2]&&
(e=encodeURIComponent(m.stringify(a[2])))}catch(k){}var f=v();"pageview"===n.toLowerCase()?(x(b.txqpid,d.HybridAiBobId,n,null,null,e,!1,f,b.foadh),a=p(b.foadh),c=q(),y(t()+"Pixel/TrackTp?pid="+(b.txqpid||"")+"&"+a+"&"+c,!0),window.setTimeout(function(){x(b.txqpid,d.HybridAiBobId,n,null,null,e,!0,f,b.foadh)},15E3)):x(b.txqpid,d.HybridAiBobId,n,a[3],a[4],e,!1,f,b.foadh)}}else if("track_d"===c){if("string"===typeof a[1]&&"string"===typeof a[2]){c=a[1];a=a[2];var h=v();C(b.txqpid,d.HybridAiBobId,c,a,
h,b.foadh)}}else if("identify"===c&&"string"===typeof a[1]){h=c=null;try{a[2]&&(c=encodeURIComponent(m.stringify(a[2]))),a[3]&&(h=encodeURIComponent(m.stringify(a[3])))}catch(k){}D(b.txqpid,d.HybridAiBobId,a[1],c,h,v(),b.foadh)}}};b.txq=function(a){this.push(a)};b.txq.prototype.push=function(a){b.txqhnd(a)};b.txqi=function(){window._txq=window._txq||[];if(window._txq)for(var a in window._txq)window._txq.hasOwnProperty(a)&&b.txqhnd(window._txq[a]);"complete"==document.readyState?window._txq=new b.txq(window._txq):
w(document,"readystatechange",function(){window._txq=new b.txq(window._txq)});b.cdh=z()};return b}(d.lib||{});d.lib.txqi();d.sendPixel=function(b){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track","PageView"])};d.sendEvent=function(b,r){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track",r])};d.sendProductView=function(b,r,m){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track","ViewContent",{content_type:"product",content_ids:[m]}])};d.MarkVisitor=function(){};d.sendAudience=function(){};
d.sendAudienceTags=function(){};return d}(window._tx||{});
