(function(){var l;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function v(a){if(!(a instanceof Array)){a=ba(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ea(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var fa=ea(this);function ha(a,b){if(b)a:{var c=fa;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&da(c,a,{configurable:!0,writable:!0,value:b})}}var ia;
if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},oa={};try{oa.__proto__=ka;ja=oa.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var pa=ia;
function qa(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(pa)pa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ub=b.prototype}
ha("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(e||"")+"_"+f++,e)}function c(e,k){this.g=e;da(this,"description",{configurable:!0,writable:!0,value:k})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0;return b});
ha("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=fa[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&da(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ra(aa(this))}})}return a});function ra(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function sa(a,b){a instanceof String&&(a+="");var c=0,d=!1,f={next:function(){if(!d&&c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f}ha("Array.prototype.keys",function(a){return a?a:function(){return sa(this,function(b){return b})}});function ua(a,b,c,d){this.o=a;this.method=b;this.version=c;this.g=d}function va(a){return!!a&&void 0!==a.omid_message_guid&&void 0!==a.omid_message_method&&void 0!==a.omid_message_version&&"string"===typeof a.omid_message_guid&&"string"===typeof a.omid_message_method&&"string"===typeof a.omid_message_version&&(void 0===a.omid_message_args||void 0!==a.omid_message_args)}function wa(a){return new ua(a.omid_message_guid,a.omid_message_method,a.omid_message_version,a.omid_message_args)}
function xa(a){var b={};b=(b.omid_message_guid=a.o,b.omid_message_method=a.method,b.omid_message_version=a.version,b);void 0!==a.g&&(b.omid_message_args=a.g);return b};function ya(a){this.o=a};function za(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];Aa(function(){return console.error.apply(console,v(b))})}function Aa(a){"undefined"!==typeof console&&console&&console.error&&a()};function Ba(a,b){if(!b)throw Error("Value for "+a+" is undefined, null or blank.");if("string"!==typeof b&&!(b instanceof String))throw Error("Value for "+a+" is not a string.");if(""===b.trim())throw Error("Value for "+a+" is empty string.");}function Ca(a){if(!a)throw Error("functionToExecute must not be truthy.");}
function Da(a,b){if(null==b)throw Error(a+" must not be null or undefined.");if("number"!==typeof b||isNaN(b))throw Error("Value for "+a+" is not a number");if(0>b)throw Error(a+" must be a positive number.");};function Ea(){return/\d+\.\d+\.\d+(-.*)?/.test("1.3.15-dev")}function Ga(){for(var a=["1","3","15"],b=["1","0","3"],c=0;3>c;c++){var d=parseInt(a[c],10),f=parseInt(b[c],10);if(d>f)break;else if(d<f)return!1}return!0};function Ha(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return"y"===a?(b&3|8).toString(16):b.toString(16)})};var Ia=eval("this"),w=function(){if("undefined"!==typeof omidGlobal&&omidGlobal)return omidGlobal;if("undefined"!==typeof global&&global)return global;if("undefined"!==typeof window&&window)return window;if("undefined"!==typeof Ia&&Ia)return Ia;throw Error("Could not determine global object context.");}();function Ja(a,b){return a&&(a[b]||(a[b]={}))};function Ka(a){return null!=a&&"undefined"!==typeof a.top&&null!=a.top}function La(a){if(a===w)return!1;try{if("undefined"===typeof a.location.hostname)return!0}catch(b){return!0}return!1};function Ma(a){this.o=a;this.handleExportedMessage=Ma.prototype.S.bind(this)}qa(Ma,ya);Ma.prototype.F=function(a){var b=void 0===b?this.o:b;if(!b)throw Error("Message destination must be defined at construction time or when sending the message.");b.handleExportedMessage(xa(a),this)};Ma.prototype.S=function(a,b){va(a)&&this.g&&this.g(wa(a),b)};function Na(a,b){this.o=b=void 0===b?w:b;var c=this;a.addEventListener("message",function(d){if("object"===typeof d.data){var f=d.data;va(f)&&d.source&&c.g&&c.g(wa(f),d.source)}})}qa(Na,ya);Na.prototype.F=function(a){var b=void 0===b?this.o:b;if(!b)throw Error("Message destination must be defined at construction time or when sending the message.");b.postMessage(xa(a),"*")};function Oa(a){try{return a.frames?!!a.frames.omid_v1_present:!1}catch(b){return!1}};var Pa=["omid","v1_VerificationServiceCommunication"],Qa=["omidVerificationProperties","serviceWindow"];function Ra(a,b){return b.reduce(function(c,d){return c&&c[d]},a)};function Sa(a){if(!a){var b;"undefined"===typeof b&&"undefined"!==typeof window&&window&&(b=window);b=Ka(b)?b:w;var c=void 0===c?Oa:c;a=[];var d=Ra(b,Qa);d&&a.push(d);a.push(Ka(b)?b.top:w);a:{a=ba(a);for(var f=a.next();!f.done;f=a.next()){b:{d=b;f=f.value;var e=c;if(!La(f))try{var k=Ra(f,Pa);if(k){var g=new Ma(k);break b}}catch(m){}g=e(f)?new Na(d,f):null}if(d=g){a=d;break a}}a=null}}if(this.g=a)this.g.g=this.nb.bind(this);else if(c=(c=w.omid3p)&&"function"===typeof c.registerSessionObserver&&"function"===
typeof c.addEventListener?c:null)this.o=c;this.wa=this.xa=0;this.F={};this.S=[];this.fa=(c=w.omidVerificationProperties)?c.injectionId:void 0}function Ta(a){var b=B;Ca(a);b.o?b.o.registerSessionObserver(a,"adloox.com-omid",b.fa):b.na("addSessionListener",a,"adloox.com-omid",b.fa)}l=Sa.prototype;l.addEventListener=function(a,b){Ba("eventType",a);Ca(b);this.o?this.o.addEventListener(a,b):this.na("addEventListener",b,a)};
function Ua(a){var b=B;Ba("url",a);w.document&&w.document.createElement?Va(b,a):b.na("sendUrl",function(){},a)}function Va(a,b){function c(f){var e=a.S.indexOf(d);0<=e&&a.S.splice(e,1);f&&f()}var d=w.document.createElement("img");a.S.push(d);d.addEventListener("load",c.bind(a,void 0));d.addEventListener("error",c.bind(a,void 0));d.src=b}
function Wa(a,b,c){var d=B;Ba("url",a);w.document?Xa(a,b,c):d.na("injectJavaScriptResource",function(f,e){f?(Ya(e,a),b()):(za("Service failed to load JavaScript resource."),c())},a)}function Xa(a,b,c){var d=w.document,f=d.body;d=d.createElement("script");d.onload=b;d.onerror=c;d.src=a;d.type="application/javascript";f.appendChild(d)}function Ya(a,b){try{eval(a)}catch(c){za('Error evaluating the JavaScript resource from "'+b+'".')}}
l.setTimeout=function(a,b){Ca(a);Da("timeInMillis",b);if(Za())return w.setTimeout(a,b);var c=this.xa++;this.na("setTimeout",a,c,b);return c};l.clearTimeout=function(a){Da("timeoutId",a);Za()?w.clearTimeout(a):this.ab("clearTimeout",a)};l.setInterval=function(a,b){Ca(a);Da("timeInMillis",b);if($a())return w.setInterval(a,b);var c=this.wa++;this.na("setInterval",a,c,b);return c};l.clearInterval=function(a){Da("intervalId",a);$a()?w.clearInterval(a):this.ab("clearInterval",a)};
function Za(){return"function"===typeof w.setTimeout&&"function"===typeof w.clearTimeout}function $a(){return"function"===typeof w.setInterval&&"function"===typeof w.clearInterval}l.nb=function(a){var b=a.method,c=a.o;a=a.g;if("response"===b&&this.F[c]){var d=Ea()&&Ga()?a?a:[]:a&&"string"===typeof a?JSON.parse(a):[];this.F[c].apply(this,d)}"error"===b&&window.console&&za(a)};l.ab=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.na.apply(this,[a,null].concat(v(c)))};
l.na=function(a,b,c){for(var d=[],f=2;f<arguments.length;++f)d[f-2]=arguments[f];this.g&&(f=Ha(),b&&(this.F[f]=b),d=Ea()&&Ga()?d:JSON.stringify(d),this.g.F(new ua(f,"VerificationService."+a,"1.3.15-dev",d)))};var ab=void 0;if(ab=void 0===ab?"undefined"===typeof omidExports?null:omidExports:ab){var bb=["OmidVerificationClient"];bb.slice(0,bb.length-1).reduce(Ja,ab)[bb[bb.length-1]]=Sa};var G=this,H=G==G.self;function J(){}function cb(a,b){a=typeof a;return b?a==b:a}function K(a){return null!==a&&cb(a,"object")}function db(a){return cb(a,"string")}function L(a){return cb(a,"number")}function M(a){return cb(a,"function")}function N(a){return cb(a,"boolean")}var eb=H?function(a){try{return a instanceof a.ownerDocument.defaultView.Element}catch(b){return!1}}:function(){return!1};function O(a){return L(a)?Math.floor(a):parseInt(a,10)}
function fb(){return(new Date).getTimezoneOffset()}var P=K(G.performance)&&M(G.performance.now)?function(){return O(G.performance.now())}:function(){return(new Date).getTime()+6E4*fb()},gb=P();function hb(a){return(a||[]).reduce(function(b,c,d){return b+d%2*c},0)}function ib(a){return 1<(a||[]).length&&0==a[0]}var jb=new Sa,B=jb.g||jb.o?jb:!1;function Q(a,b){return(B||G).setTimeout(a,b)}function kb(a){(B||G).clearTimeout(a)}function lb(a,b){return(B||G).setInterval(a,b)}var mb=!1,nb={},ob=[],pb=0;
function qb(a,b){if(null==b.H||b.H==a.H)try{b.pa.apply(b.context||null,[a.H,a.sb].concat(a.bb))}catch(c){a.H.l("error",{err:c.message,"%b":c.stack})}}function rb(){L(mb)&&kb(mb);for(mb=!0;pb<ob.length;pb++)for(var a=ob[pb],b=nb[a.name]||[],c=0;c<b.length;c++)qb(a,b[c]);mb=!1}function sb(a,b,c){for(var d=[],f=2;f<arguments.length;++f)d[f-2]=arguments[f];J.apply(null,["fire",b].concat(v(d)));ob.push({H:a,sb:P(),name:b,bb:d});!0!==mb&&(a&&a.ended?rb():!1===mb&&(mb=Q(rb,0)))}
function R(a,b,c,d){nb[b]||(nb[b]=[]);a={H:a,pa:c,context:d};nb[b].push(a);for(c=0;c<pb;c++)d=ob[c],d.name==b&&(J.apply(null,["fire [playback]",d.name].concat(v(d.bb))),qb(d,a))}function tb(a,b,c){for(var d=nb[b]||[],f=d.length;0<f--;){var e=d[f];e.H!=a||e.pa!=c&&e.pa.Za!=c||nb[b].splice(f,1)}}
var ub=H?function(a){var b=G.document.createElement("a");b.href=a;return b}:function(a){var b=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?/;a=a.match(b)||"about:blank".match(b);a={protocol:a[1]||"",hostname:a[3]||"//",pathname:a[5]||"/",search:a[6]||"",hash:a[8]||""};a.host=a.hostname.replace(/:[0-9]+$/,"");a.port=O(a.hostname.replace(/^.*:([0-9]+)$/,"$1"));if(isNaN(a.port))switch(a.protocol){case "http":a.port=80;break;case "https":a.port=443;break;default:a.port=0}a.href=a.protocol+
"//"+a.hostname+a.path+a.search+a.hash;a.origin=a.protocol+"//"+a.hostname;return a};function vb(a){return encodeURIComponent(a).replace(/[!'()*]/g,function(b){return"%"+b.charCodeAt(0).toString(16)})}function wb(a){var b={};if(!a.length)return b;a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=",2);if(d[0].length){var f=decodeURIComponent(d[0]);d=d[1];try{d=decodeURIComponent(d)}catch(e){}d=d||!0;void 0===b[f]?b[f]=[d]:b[f].push(d)}}return b}function xb(a){return a[a.length-1]}var yb;
if(H){var zb;if(!(zb=G.document.currentScript))a:{for(var Ab=new RegExp("/"+"tfav_adl_55.js".replace(".","\\.")+"(?:[#?]|$)"),Cb=G.document.scripts,Db=Cb.length;0<Db--;)if(Cb[Db]&&Cb[Db].src&&Cb[Db].src.match(Ab)&&!Cb[Db].getAttribute("data-adloox-sid")){zb=Cb[Db];break a}zb=null}yb=zb}else yb=void 0;var S=yb,T=S?ub(S.src):void 0;
function Eb(a){var b=this;this.A=a;this.u=this.v=this.g=null;this.o={};this.F=this.V=this.ea=null;a.subscribe("rollstate.visi.run",function(){b.F=!0});a.subscribe("rollstate.visi.pause",function(){b.F=!1});this.J=this.duration=this.ba=void 0;this.ya=this.oa=null;this.data=this.P.bind(this);a.subscribe("adunit",this.S,this)}Eb.prototype.Ia=function(){var a=!1,b;for(b in this.o){var c=this.o[b];a=a||c.T;if(c.ratio<this.u.L.aa||c.L||c.state)return!1}return a?!0:void 0};
Eb.prototype.Ja=function(){if(this.u.B){var a=!1,b;for(b in this.o){var c=this.o[b];a=a||c.T;if(c.ratio<(this.u.B.aa||NaN)||c.B||c.state)return!1}return a?!0:void 0}};
Eb.prototype.S=function(a,b,c){function d(h){!m&&c.video?Fb(e,h,c):!m&&eb(c.slot)?Gb(h,c):h.l("rollstate.visi.run")}function f(h){e.g=h||null;!e.g&&e.v&&e.A.C.va&&(e.g=e.A.C.va(e.v));e.g&&(e.u.L.j={x:O(e.g.width*Math.sqrt(e.u.L.aa)/2),y:O(e.g.height*Math.sqrt(e.u.L.aa)/2)},e.u.B&&(e.u.B.j={x:O(e.g.width*Math.sqrt(e.u.B.aa)/2),y:O(e.g.height*Math.sqrt(e.u.B.aa)/2)}));a.l("visi.rect",e.g)}var e=this,k=.5,g=1E3;switch(a.m.creatype){case 6:case 23:this.V=200;g=2E3;break;default:this.V=100,!this.A.C.s.Ra&&
this.g&&242500<=this.g.width*this.g.height&&(k=.3)}this.u={L:{aa:Math.max(k,(a.m.custom1area||0)/100),time:Math.max(g,1E3*(a.m.custom1sec||0))}};a.ca=Math.min(a.ca,this.u.L.time);a.m.custom2area&&a.m.custom2sec&&(this.u.B={aa:a.m.custom2area/100,time:1E3*a.m.custom2sec},a.ca=Math.min(a.ca,this.u.B.time));eb(c.slot)&&(c.slot.setAttribute("data-adloox-type","slot"),c.slot.setAttribute("data-adloox-sid",a.O),this.v=c.slot);eb(c.video)&&(c.video.setAttribute("data-adloox-type","video"),c.video.setAttribute("data-adloox-sid",
a.O),this.v=c.video);a.subscribe("geometry",function(h,n,r){f(r)});f(c.rect);Hb(this);var m=1==this.A.m.creatype;a.j.size=function(){var h=e.g;return null===h?void 0:h.width+"x"+h.height};a.j.pdv=function(){return e.ba};a.j.ad=function(){return e.duration};a.j.ad2=function(){return e.J};a.j.p_d_v=function(){return hb(e.ba)/1E3};a.j.a_d=function(){return hb(e.duration)/1E3};a.j.wasatf=function(){return 2*~~ib(e.duration)};a.j.visible=function(){return 2*~~e.oa};m?(a.j.wasatf=2,a.j.a_d2=function(){return hb(e.ba)/
1E3},a.j.wasatf2=2,a.j.visible2=function(){return 2*~~(2E3<=hb(e.ba))}):this.u.B&&(a.j.a_d2=function(){return hb(e.J)/1E3},a.j.wasatf2=function(){return 2*~~ib(e.J)},a.j.visible2=function(){return 2*~~e.ya});a.j.d9=function(){var h=[],n;for(n in e.o)h.push(n);return h};this.F=!1;a.ra&&a.m.targetelt.length&&"hidden"==this.v.style.visibility?a.subscribe("fw",d):d(a,b)};
function Fb(a,b,c){function d(){b.l("rollstate.visi.run")}c.video.addEventListener("playing",d,b.C.s.G?!1:{passive:!0});c.video.addEventListener("pause",function(){b.l("rollstate.visi.pause")},b.C.s.G?!1:{passive:!0});if(c.video.paused||3>(c.video.readyState||0))var f=lb(function(){a.F?(B||G).clearInterval(f):0<c.video.currentTime&&d()},200);else d()}
function Gb(a,b){a.R[2]=P();var c=0;a.R[3]=0;var d=[].concat(v(b.slot.getElementsByTagName("*")));d.push(b.slot);var f=[];d.forEach(function(e){var k="";switch(e.tagName){case "IMG":e.src&&(k=e.src);break;default:var g=K(e.style)&&e.style["background-image"];g&&(g=g.match(/^url\("?([^")]+)"?\)$/))&&(k=g[1])}if(/^https?:/.test(k)&&"none"!=e.style.display&&"none"!=e.style.visibility){a.R[3]+=1;var m=function(){m=J;--c||(a.R[5]=P(),a.l("rollstate.visi.run"))};g=function(n,r){m(n,r)};var h="IMG"==e.tagName?
e:new Image;h.onload=h.onerror=g;"IMG"!=e.tagName&&(h.src=k);h.complete||4===h.readyState||0<h.naturalWidth?m=J:(c++,f.push(g))}});(a.R[4]=c)||(a.R[5]=P());c?Q(function(){f.forEach(function(e){return e(null,!0)})},2E3):a.l("rollstate.visi.run")}
function Hb(a){function b(e){if(null!==e[0]&&null!==e[1]&&null!==e[2])return e[1]&&(e[0]||e[2])}var c=[];a.A.R[9]=0;a.A.subscribe("impression",function(e){function k(){k=J;h.ya=!0;e.l("viewable.custom")}function g(){g=J;h.oa=!0;e.l("viewable.iab")}function m(p,q,u){if(!e.ma)return u;u||(u=[0]);u.length%2==~~p&&u.push(0);u[u.length-1]+=q;return u}var h=this,n=P(),r=lb(function(){var p=P()-n;n+=p;c.forEach(function(u){return u()});h.ba=m(!0,p,h.ba);e.R[9]+=h.A.C.hidden?0:p;if(h.ea){var q=h.Ia();N(q)&&
(h.duration=m(q,p,h.duration),q&&h.duration&&0==h.duration.length%2&&h.duration[h.duration.length-1]>h.u.L.time&&g());q=h.Ja();N(q)&&(h.J=m(q,p,h.J),q&&h.J&&0==h.J.length%2&&h.J[h.J.length-1]>h.u.B.time&&k())}},this.V);e.subscribe("end",function(){(B||G).clearInterval(r)})},a);var d=1==a.A.m.creatype,f;(function(){H&&"mraid"!=a.A.C.type&&a.A.C.s.da&&!a.A.C.s.ia&&c.push(function(){a.P({id:"focus",state:a.A.C.Da})})})();(function(){H&&-1==["mraid","omid"].indexOf(a.A.C.type)&&c.push(function(){a.P({id:"page",
state:a.A.C.hidden})})})();(function(){function e(){a.P({id:"takeover",T:!0,state:Ib(W(a.v)).y>Jb(a.v).height})}H&&d&&a.v&&(a.A.subscribe("geometry",e),e())})();(function(){if(H&&!d&&a.v){var e=[a.u.L.aa];a.u.B&&e.push(a.u.B.aa);try{f=new IntersectionObserver(function(k){a.P({id:"intersection",T:!0,ratio:k[0].intersectionRatio})},{threshold:e}),a.P({id:"intersection",Z:!1}),f.observe(a.v),a.A.subscribe("end",f.disconnect.bind(f))}catch(k){}}})();(function(){function e(){e=function(){var k=NaN;if(a.g){k=
a.v;for(var g=a.g,m=g.width,h=g.height;k;){var n=Jb(k);m=Math.max(Math.min(m,m-Math.abs(Math.min(0,g.left))-Math.abs(Math.min(0,n.width-g.right))),0);h=Math.max(Math.min(h,h-Math.abs(Math.min(0,g.top))-Math.abs(Math.min(0,n.height-g.bottom))),0);(k=a.A.C.frameElement(k))&&(g=a.A.C.va(k))}k=m*h/(a.g.width*a.g.height)}a.P({id:"classic",T:!0,ratio:k})};e()}H&&!d&&a.v&&!f&&(a.P({id:"classic",Z:!1}),a.A.subscribe("visi.rect",function(){e()}))})();(function(){function e(){var k={id:"element",T:!0},g=a.v.ownerDocument,
m=[a.g.left+O(a.g.width/2),a.g.top+O(a.g.height/2)],h=!g.elementFromPoint(m[0],m[1]);k.L=b([!g.elementFromPoint(m[0]-a.u.L.j.x,m[1]-a.u.L.j.y),h,!g.elementFromPoint(m[0]+a.u.L.j.x,m[1]+a.u.L.j.y)]);a.u.B&&(k.B=b([!g.elementFromPoint(m[0]-a.u.B.j.x,m[1]-a.u.B.j.y),h,!g.elementFromPoint(m[0]+a.u.B.j.x,m[1]+a.u.B.j.y)]));a.P(k)}H&&!d&&a.v&&!f&&!a.A.C.s.da&&a.A.C.s.G&&c.push(e)})();(function(){function e(){var k={IMG:!0,CANVAS:!0,VIDEO:!0,SVG:!0,IFRAME:!0},g={id:"elements",T:!0},m=[a.g.left+O(a.g.width/
2),a.g.top+O(a.g.height/2)];m=a.v.ownerDocument.elementsFromPoint(m[0],m[1]);if(null!==m){var h=m.filter(function(u){return k[u.tagName]}),n=h.indexOf(a.v);m=a.v.hidden;var r=1<h.length,p=0<n;n=.3>h.slice(0,n+1).reduce(function(u,x){return u*W(x).getComputedStyle(h[0]).getPropertyValue("opacity")},1);g.state=m||n;var q=[];m&&q.push("hidden");r&&q.push("stacked");p&&q.push("covered");n&&q.push("invisible");0<q.length&&(a.A.j.view=q.join(","))}a.P(g)}H&&!d&&a.v&&M(G.document.elementsFromPoint)&&c.push(e)})();
(function(){function e(h){e.hidden[h.i]=h.h;h={id:"animation",Z:e.hidden.every(function(n){return void 0!==n}),T:!0};h.L=b([e.hidden[0],e.hidden[2],e.hidden[1]]);a.u.B&&(h.B=b([e.hidden[3],e.hidden[2],e.hidden[4]]));a.P(h)}e.ob=function(){function h(p){e.hidden[p]=void 0;var q=r.createElement("iframe");q.style.position="absolute";q.style["pointer-events"]="none";q.style["z-index"]=e.cb+1;q.style["border-style"]="none";q.style["background-color"]="transparent";q.style.width=q.style.height="8px";if(2==
p)q.style.top=q.style.left="50%";else{var u=50-O(100*(3<=p?a.u.B:a.u.L).j.x/a.g.width)+"%";p%3?q.style.top=q.style.left=u:q.style.bottom=q.style.right=u}u=r.createElement("html");var x=r.createElement("head"),t=r.createElement("script");t.innerText="var l, w, h = null, f = function(n){ clearTimeout(w); var hh = n ? n - l > "+Math.floor(.9*a.V)+" : true; if (h != hh) { h = hh; parent.postMessage({ i: "+p+", h: h }, '*') }; if (n) setTimeout(q, "+a.V+") }, q = function(){ l = performance.now(); w = setTimeout(f, "+
a.V+"); requestAnimationFrame(f) }; onload = q";x.appendChild(t);u.appendChild(x);q.sandbox="allow-scripts";q.srcdoc=u.outerHTML;q.onload=function(){e.sources[p]=q.contentWindow};r.body.appendChild(q)}e.sources=[];e.hidden=[];var n=e.proxy.contentWindow,r=n.document;n.onmessage=function(p){e.sources.forEach(function(q){q===p.source&&e(p.data)})};for(n=0;n<3+(a.u.B?2:0);n++)h(n);a.A.subscribe("visi.rect",function(){var p=Ib(W(a.v)),q=e.proxy.style;q.top=O(a.g.top+p.y)+"px";q.left=O(a.g.left+p.x)+"px";
q.width=a.g.width+"px";q.height=a.g.height+"px"})};if(H&&!d&&a.v&&!f&&(!a.A.C.s.da||a.A.C.s.ia)&&M(G.requestAnimationFrame)&&!a.A.C.s.G){a.P({id:"animation",Z:!1});var k=W(a.v).document;e.proxy=k.createElement("iframe");e.proxy.setAttribute("data-adloox-type","proxy");e.proxy.setAttribute("data-adloox-sid",a.A.O);var g=function(){Q(function(){if(e.proxy){try{e.proxy.parentNode.removeChild(e.proxy)}catch(h){}delete e.proxy}},0)};e.proxy.onload=function(){try{e.proxy.contentWindow.document&&e.ob()}catch(h){g(),
this.P({id:"animation",Z:!0,state:!1})}};var m=W(e.proxy).getComputedStyle(e.proxy);e.cb=O(m.getPropertyValue("z-index")||0)-1E3;m=e.proxy.style;m.position="absolute";m["pointer-events"]="none";m["z-index"]=e.cb;m["border-style"]="none";m["background-color"]="transparent";k.body.appendChild(e.proxy);a.A.subscribe("end",g)}})();a.A.R[6]=P();a.A.subscribe("visi.booted",function(e){e.R[7]=P()});a.ea=!1;Kb(a)}Eb.prototype.P=function(a){this.o[a.id]=a;!1===this.ea&&Kb(this)};
function Kb(a){var b=!0,c;for(c in a.o)b=b&&!1!==a.o[c].Z;b&&(a.ea=!0,a.oa=!1,a.ya=!1,a.A.l("visi.booted"))}function Lb(a){var b=this;this.A=a;this.u=this.v=null;this.g={};this.o=this.V=this.ea=null;a.subscribe("rollstate.audio.run",function(){b.o=!0});a.subscribe("rollstate.audio.pause",function(){b.o=!1});this.J=this.duration=void 0;this.Aa=this.za=null;this.data=this.P.bind(this);a.subscribe("adunit",this.F,this)}
Lb.prototype.Ia=function(){var a=!1,b;for(b in this.g){var c=this.g[b];a=a||c.T;if(c.muted||c.ratio<this.u.L.volume||c.L||c.state)return!1}return a?!0:void 0};Lb.prototype.Ja=function(){if(this.u.B){var a=!1,b;for(b in this.g){var c=this.g[b];a=a||c.T;if(c.muted||c.ratio<(this.u.B.volume||NaN)||c.B||c.state)return!1}return a?!0:void 0}};
Lb.prototype.F=function(a,b,c){function d(g){f.v?Mb(f,g):g.l("rollstate.audio.run")}var f=this,e=Number.MIN_VALUE;switch(a.m.creatype){case 6:case 23:this.V=200;break;default:this.V=100}this.u={L:{volume:Math.max(e,(a.m.custom1vol||0)/100),time:Math.max(2E3,1E3*(a.m.custom1volsec||0))}};a.ca=Math.min(a.ca,this.u.L.time);a.m.custom2vol&&a.m.custom2volsec&&(this.u.B={volume:a.m.custom2vol/100,time:1E3*a.m.custom2volsec},a.ca=Math.min(a.ca,this.u.B.time));if(eb(c.slot)){c.slot.setAttribute("data-adloox-type",
"slot");c.slot.setAttribute("data-adloox-sid",a.O);e=[c.slot].concat(v(c.slot.getElementsByTagName("*")));for(var k=0;k<e.length;k++)if(N(e[k].muted)&&L(e[k].volume)&&M(e[k].addEventListener)){this.v=e[k];break}}eb(c.video)&&L(c.video.volume)&&(c.video.setAttribute("data-adloox-type","video"),c.video.setAttribute("data-adloox-sid",a.O),this.v=c.video);Nb(this);a.j.aud=function(){return f.duration};a.j.aud2=function(){return f.J};this.o=!1;a.ra&&a.m.targetelt.length&&1==(this.v||{}).defaultMuted?a.subscribe("fw",
d):d(a,b)};
function Mb(a,b){function c(f){b.audio.data({id:"audio",T:!0,ratio:f.volume,muted:f.muted})}function d(){b.l("rollstate.audio.run")}a.v.addEventListener("playing",d,b.C.s.G?!1:{passive:!0});a.v.addEventListener("pause",function(){b.l("rollstate.audio.pause")},b.C.s.G?!1:{passive:!0});a.v.addEventListener("volumechange",function(f){f=f.target;a.o&&f.muted?b.l("rollstate.audio.pause"):a.o||f.muted||b.l("rollstate.audio.run");c(f)},b.C.s.G?!1:{passive:!0});c(a.v);!a.v.paused&&3<=a.v.readyState&&!a.v.muted&&
d()}
function Nb(a){a.A.subscribe("impression",function(b,c){function d(){d=J;k.Aa=!0;b.l("audible.custom")}function f(){f=J;k.za=!0;b.l("audible.iab")}function e(g,m,h){if(!b.ma)return h;h||(h=[0]);h.length%2==~~g&&h.push(0);h[h.length-1]+=m;return h}var k=this;b.subscribe("audio.booted",function(g,m){var h=this;this.Aa=this.za=!1;m=Math.max(c,m);var n=lb(function(){var r=P()-m;m+=r;var p=h.Ia();N(p)&&(h.duration=e(p,r,h.duration),p&&h.duration&&0==h.duration.length%2&&h.duration[h.duration.length-1]>
h.u.L.time&&f());p=h.Ja();N(p)&&(h.J=e(p,r,h.J),p&&h.J&&0==h.J.length%2&&h.J[h.J.length-1]>h.u.B.time&&d())},this.V);g.subscribe("end",function(){(B||G).clearInterval(n)})},this)},a);a.ea=!1;Ob(a)}Lb.prototype.P=function(a){this.g[a.id]=a;!1===this.ea&&Ob(this)};function Ob(a){var b=!0,c;for(c in a.g)b=b&&!1!==a.g[c].Z;b&&(a.ea=!0,a.A.l("audio.booted"))}
function Pb(a,b){this.ta="__"+a+"api";this.fa="tcf"==a?2:1;this.o=b;this.g=null;if("function"==typeof G[this.ta])b=G[this.ta];else a:{b=G;do{b=b.parent;var c=void 0;try{c=b.frames[this.ta+"Locator"]}catch(d){}if(c){b=Qb(c.parent);break a}}while(b!=G.top);b=this.S}this.g=b;this.F="get"+("tcf"==a?"TC":"USP")+"Data";this.hb=2E3}function Rb(a,b){b=[a.F,a.fa,b];a.o&&b.push([a.o]);a.g.apply(null,b)}Pb.prototype.S=function(a,b,c){c({msg:"CMP not found"},!1)};
function Qb(a){var b={},c={};G.addEventListener("message",function(d){var f=this.ta+"Return",e=d.data[f]&&d.data[f].callId;e in b&&(kb(c[e]),delete c[e],b[e](d.data[f].returnValue,d.data[f].success),delete b[e])},!1);return function(d,f,e,k){var g=Math.random().toString(16).substr(2);b[g]=e;c[g]=Q(function(){e({msg:"CMP deadline"});delete b[g];delete c[g]},this.hb);var m={};m[this.ta+"Call"]={command:d,parameter:k,version:f,callId:g};a.postMessage(m,"*")}}
function Sb(a,b){var c=this;this.C=a;this.R=[gb];this.data=null;a=db(b)?[b]:[];T&&(T.hash&&a.push(T.hash.slice(1)),T.search&&a.push(T.search.slice(1)));L(G.adloox_pc_viewed)&&a.push("custom2area="+G.adloox_pc_viewed);L(G.adloox_time_viewed)&&a.push("custom2sec="+G.adloox_time_viewed);db(G.adloox_target)&&a.push("targetelt="+G.adloox_target);var d=wb(a.join("&"));this.m=d;a=[];for(var f in d)if(d[f]=d[f].filter(function(m){return!!m.length}),d[f].length){var e=xb(d[f]);if(f.match(/^id[0-9]+$/)){var k=
O(f.substr(2));0<k&&(d[f]=a[k]=e)}else switch(f){case "fwtype":e=O(e);d[f]=1<=e&&4>=e?e:1;break;case "creatype":case "platform":case "tagid":case "custom1area":case "custom2area":case "custom1vol":case "custom2vol":d[f]=O(e);0<d[f]||delete d[f];break;case "custom1sec":case "custom2sec":case "custom1volsec":case "custom2volsec":d[f]=parseFloat(e);0<d[f]||delete d[f];break;case "ping":d[f]=O(e);isNaN(d[f])&&delete d[f];break;case "id":case "vast":case "url":case "urlt":case "urle":d[f]=e;break;case "client":delete d[f];
break;case "vast_skiptracking":d[f]=!0}}else delete d[f];"na"==a[20]&&(a[20]="614b730");a[20]=a[20]||"614b730";d.client="weborama";d.creatype||(d.creatype=2);d.targetelt||(d.targetelt=[]);for(f=d.targetelt.length;0<f--;)d.targetelt[f].length||d.targetelt.splice(f,1);f=1==d.creatype;d.fwtype=f?2:d.fwtype||1;this.ca=Infinity;this.j={};"russia"==a[12]&&(d.fwtype=2);if(d.url||d.urlt)d.fwtype=4;d.url||(d.url="https://data00.adlooxtracking.com/ads");d.urlt||(d.urlt=d.url+"/ic5.php");d.urle||(d.urle=d.url+
"/err.php");d.transaction_id=G.tab_adloox_transaction_id_weborama instanceof Array?G.tab_adloox_transaction_id_weborama[0]:d.transaction_id;this.ra=!f&&!(2==d.fwtype||4==d.fwtype);this.g=null;this.O=d.id||Math.floor(1E11*Math.random()+1).toString();this.subscribe=R.bind(this,this);this.unsubscribe=tb.bind(this,this);this.l=sb.bind(this,this);this.start=this.mb.bind(this);this.end=this.Sa.bind(this);this.Ba=this.gb.bind(this);this.ma=null;this.subscribe("rollstate.run",function(){c.ma=!0});this.subscribe("rollstate.pause",
function(){c.ma=!1});this.ended=this.Pa=!1;this.N={sm:this.C.type};this.I=new Eb(this);this.audio=new Lb(this);this.o=null;switch(d.fwtype){case 2:f="log";break;case 3:f="wl";break;default:f=d.fwtype}this.l("config");this.j.d1=function(){function m(h){return h.replace(/[#&?]id[0-9]+=[^&]+/g,"")}try{return JSON.stringify({tag_search:T&&T.search?m(T.search.slice(1)):void 0,tag_hash:T&&T.hash?m(T.hash.slice(1)):void 0,ext:db(b)?m(b):void 0,wpc:L(G.adloox_pc_viewed)?G.adloox_pc_viewed:void 0,wtm:L(G.adloox_time_viewed)?
G.adloox_time_viewed:void 0,wtg:db(G.adloox_target)?G.adloox_target:void 0})}catch(h){}};this.j.adloox_io=1;this.j.client=d.client;this.j.campagne="55";this.j.banniere="0";this.j.visite_id=this.O;this.j.seq=function(){var m=0;return function(){return m++}}();this.j.timezone=fb;this.j.js="tfav_adl_55.js";this.j.date_regen="2021-12-14 10:16:19";this.j.plat=d.platform;this.j.tagid=d.tagid;this.j.fw=f;this.j.version=d.fwtype;this.j.type_crea=function(){return d.creatype};this.j.sl=function(){var m=[],
h;for(h in c.N){var n=void 0;try{n=JSON.stringify(c.N[h])}catch(r){n="null"}m.push(['"'+h+'"',n].join(":"))}return m.length?m:void 0};for(f=1;21>f;f++)void 0!==a[f]&&(this.j["id"+f]=a[f]);this.j.p_d=function(){return(P()-gb)/1E3};this.j.d5=function(){return c.R};a={px_imp:"impression",px_view:"viewable.iab",px_viewc:"viewable.custom"};for(var g in a)this.subscribe(a[g],function(m){for(var h=(d[m]||[]).length;0<h--;)this.l("send",d[m][h])}.bind(this,g));this.subscribe("send.visi",this.Ka,this);this.subscribe("start",
function(){c.m.ping&&c.subscribe("impression",c.ib,c);c.l("send.tracked",c.m.urlt,c.j)});this.subscribe("end",function(){c.Ka(!0);var m;for(m=(d.bridge||[]).length;0<m--;)c.l("send",d.bridge[m]);if(N(c.ma)){var h;null===c.I.oa?h="px_viewu":!1===c.I.oa&&(h="px_viewn");for(m=(d[h]||[]).length;0<m--;)c.l("send",d[h][m])}});this.subscribe("adunit",function(m){c.R[1]=P();Q(function(){function h(){h=J;c.ma=!0;m.l("impression")}var n=null;m.I.v?n="visi":m.audio.v&&(n="audio");n?m.subscribe("rollstate."+
n+".run",function(){h()}):h()},0)})}l=Sb.prototype;l.mb=function(){function a(){b.Pa=!0;b.l("start")}var b=this,c=Q(function(){this.Sa()}.bind(this),117E4);this.subscribe("end",function(){kb(c)});this.C.La?R(null,"manager.booted",a):a()};l.Sa=function(){this.ended||(this.ended=!0,this.R[8]=P(),this.l("end"))};l.gb=function(a,b){this.m[a]=(this.m[a]||[]).concat(b)};
l.ib=function(){function a(){b.ended||(d=Q(function(){b.Ka();c=!0;a()},Math.floor(1E3*(c?f+f/4*Math.random():e+.5+2*Math.random()))),f=Math.min(64,2*Math.max(f,1)))}var b=this,c,d,f=1,e=this.ca/1E3;a();this.subscribe("viewable.iab",function(){kb(d);e=-.5;f=0;a()})};l.Ka=function(a){if(this.Pa&&(!this.ended||a)&&!this.g){var b=P();!a&&500>b-this.o||(this.o=b,this.l("send",this.m.urlt,this.j))}};
function Tb(a){this.type=a||"base";this.wa=!1;this.La=1;this.U={};this.Da=this.hidden=null;this.s={};this.fa=this.eb.bind(this);this.g=this.fb.bind(this);R(null,"fw",this.sa,this);R(null,"send.tracked",this.lb,this);R(null,"send",this.jb,this);R(null,"error",this.kb,this)}l=Tb.prototype;l.eb=function(){this.La++};l.fb=function(){--this.La||sb(null,"manager.booted")};l.sa=function(a,b,c){a.g=c.state;a.g&&a.end()};l.jb=function(a,b,c,d){this.ja(a,c,d)};l.ja=function(){throw"__send unsupported";};
l.lb=function(a,b,c,d){this.Ga(a,c,d)};l.Ga=function(){throw"__send_tracked unsupported";};l.kb=function(a,b,c){this.wa||(this.wa=!0,c.client="weborama"+(a.m.client?":"+a.m.client:""),c.js="tfav_adl_55.js",c.visite_id=a?a.O:0,this.ja(a,a.m.urle,c));this.wa=!1};
l.url=function(a,b,c){var d=1==a.m.creatype;M(b)&&(b=b());if(db(b)&&b==b.trim()){if(c){var f=[],e;for(e in c)if(c.hasOwnProperty(e)&&void 0!==c[e]){var k=c[e];k instanceof Array||(k=[k]);for(var g=0;g<k.length;g++){var m=M(k[g])?k[g]():k[g];void 0!==m&&f.push(vb(e)+"="+vb(m))}}c=f.join("&")}else c=null;b+=c?(-1==b.indexOf("?")?"?":"&")+c:"";return b.split("[ADL_SID]").join(a?a.O:0).split("[ADL_TYPE]").join(a?a.I.v?"vis":a.audio.v?"aud":"???":"").split("[ADL_IMP]").join(~~(a&&N(a.ma))).split("[ADL_VW]").join(a&&
N(a.I.oa)?~~a.I.oa:"").split("[ADL_VWC]").join(a?d?~~(2E3<=hb(a.I.ba)):N(a.I.ya)?~~a.I.ya:"":"").split("[ADL_ATF]").join(a&&void 0!==a.I.duration?~~ib(a.I.duration):"").split("[ADL_AD]").join(a&&N(a.audio.za)?~~a.audio.za:"").split("[ADL_ADC]").join(a&&N(a.audio.Aa)?~~a.audio.Aa:"").split("[ADL_DP]").join(a&&void 0!==a.I.ba?a.I.ba:"").split("[ADL_DV]").join(a&&void 0!==a.I.duration?a.I.duration:"").split("[ADL_DVC]").join(a&&void 0!==a.I.J?a.I.J:"").split("[ADL_DA]").join(a&&void 0!==a.audio.duration?
a.audio.duration:"").split("[ADL_DAC]").join(a&&void 0!==a.audio.J?a.audio.J:"").split("[ADL_FW]").join(a&&N(a.g)?~~a.g:"").split("[ERRORCODE]").join(901).split(/(?:\[|$\{|%%)(?:RANDOM|CACHEBUST[A-Z]*)(?:\]|\}|%%)/i).join(Math.floor(99E6*Math.random()+1E6)).split(/\[TIMESTAMP\]/i).join(vb((new Date).toISOString()))}};
function X(a){function b(){for(var e in d.U)d.U[e].Pa&&d.U[e].l("send.visi")}function c(){for(var e in d.U)d.U[e].end()}Tb.call(this,a);var d=this;this.s=Ub(this);G.addEventListener("beforeunload",c,this.s.G?!0:{capture:!0,passive:!0});G.addEventListener("onpagehide"in G?"pagehide":"unload",function(e){if(e.persisted)return b();c()},this.s.G?!0:{capture:!0,passive:!0});this.hidden="hidden"==G.document.visibilityState;this.S=!this.hidden;G.document.addEventListener("visibilitychange",function(){d.hidden=
"hidden"==G.document.visibilityState;d.S=d.S||!d.hidden;"unloaded"==G.document.visibilityState?c():d.hidden&&b()},this.s.G?!1:{passive:!0});this.s.da&&!this.s.ia&&"mraid"!=a&&(this.Da=!G.top.document.hasFocus(),G.top.addEventListener("focus",function(){d.Da=!1},this.s.G?!1:{passive:!0}),G.top.addEventListener("blur",function(){d.Da=!0},this.s.G?!1:{passive:!0}));R(null,"adunit",function(e,k,g){function m(){e.ended||m.Xa||(m.Xa=!0,Q(function(){m.Xa=!1;e.l("geometry")},200))}if(g.video||g.slot)(g.video||
g.slot).addEventListener("mouseenter",m,d.s.G?!1:{passive:!0}),(g.video||g.slot).addEventListener("mouseleave",m,d.s.G?!1:{passive:!0});for(k=g.video&&W(g.video)||g.slot&&W(g.slot)||G;;)try{k.addEventListener("resize",m,d.s.G?!1:{passive:!0});k.addEventListener("scroll",m,d.s.G?!1:{passive:!0});if(k==G.top)break;k=k.parent}catch(h){break}});R(null,"config",function(e){Vb(e.m.url);for(var k=(e.m.bridge||[]).length;0<k--;)Vb(e.m.bridge[k]);"ping"in e.m||!(d.hidden||d.s.Ra||d.s.ia)||"vpaid"==a||(e.m.ping=
1);Wb(e)});R(null,"impression",function(e){(e.m.js_imp||[]).forEach(function(k){var g=G.document.createElement("iframe");g.style.display="none";g.src="javascript:false";g.onload=function(){var m=g.contentWindow.document.createElement("script");m.src=d.url(e,k);g.contentWindow.document.head.appendChild(m)};Xb(g,S);e.subscribe("end",function(){g.parentNode.removeChild(g)})});(e.m.html_imp||[]).forEach(function(k){var g=G.document.createElement("iframe");g.style.display="none";g.src=k;Xb(g,S);e.subscribe("end",
function(){g.parentNode.removeChild(g)})})});M(G.navigator.getUserAgent)&&(this.fa(),G.navigator.getUserAgent().then(function(e){R(null,"config",function(k){for(var g in e)db(e[g])&&e[g].length&&(k.j["ch_ua_"+g]=e[g])});d.g()}));var f=new Pb("tcf",93);this.fa();Rb(f,function(e,k){R(null,"config",function(g){g.j.tc=N(k)&&K(e)?e.tcString:""});d.g()});f=new Pb("usp");this.fa();Rb(f,function(e,k){R(null,"config",function(g){g.j.usp=N(k)&&K(e)?e.uspString:""});d.g()})}qa(X,Tb);
function Ib(a){var b=a.document;b=b.documentElement||b.body.parentNode||b.body;var c=void 0!==a.pageXOffset;return{x:O(c?a.pageXOffset:b.scrollLeft),y:O(c?a.pageYOffset:b.scrollTop)}}function W(a){a=a.ownerDocument;return!!a&&(a.defaultView||a.parentWindow)}function Jb(a){var b=W(a);a=a.ownerDocument.documentElement;return{width:Math.max(a.clientWidth,b.innerWidth||0),height:Math.max(a.clientHeight,b.innerHeight||0)}}l=X.prototype;l.frameElement=function(a){a.ownerDocument&&(a=W(a));try{return a.frameElement}catch(b){return null}};
l.va=function(a){var b=null;try{b=a.getBoundingClientRect(),b={left:O(b.left),right:O(b.right),top:O(b.top),bottom:O(b.bottom)},b.width=b.right-b.left,b.height=b.bottom-b.top}catch(c){}return b};
function Ub(a){var b={};b.qb=!!G.InstallTrigger;b.rb=/Apple/.test(G.navigator.vendor)&&!/CriOS|FxiOS/.test(G.navigator.userAgent);b.$a=!!G.opera;b.pb=!b.$a&&!!G.chrome;b.G="documentMode"in G.document;b.tb=!b.G&&/Edge?\/[1-9]/.test(G.navigator.userAgent);b.Ra=/Android|webOS|iP(?:hone|od|ad)|BlackBerry|mobi|Opera Mini/i.test(G.navigator.userAgent);b.ia=/Version\/[0-9.]+ Chrome\/[0-9.]+ Mobile|iP(?:hone|od|ad).*AppleWebKit(?!.*Version\/[0-9.]+)|; wv/.test(G.navigator.userAgent);b.Fa=G!=G.top;try{b.da=
!!G.top.document}catch(d){b.da=!1}b.Wa=(G.location.ancestorOrigins||[])[0];b.title=G.document.title||"";b.la="";b.ga=function(){function d(f,e,k){k?(f=(f+"").slice(k).lastIndexOf(e),-1!=f&&(f+=k)):f=(f+"").lastIndexOf(e);return 0<=f?f:!1}try{return b.la="1: parent.parent.location.href",G.parent.parent.location.href}catch(f){try{return b.la="2: parent.location.href",G.parent.location.href}catch(e){if(d(e.message,"<",0))return e.message.substring(d(e.message,"<",0)+1,d(e.message,">",0));b.la="3:  location.href";
return G.location.href}}}()||"";var c=b.ga;if(b.Fa){b.ga=G.document.referrer;b.la="6: top != window -> GLOBAL.document.referrer "+location.href;b.da&&(b.ga=G.location.href,b.la="7: top != window & friendly -> GLOBAL.location.href "+document.referrer);"about:blank"==b.ga&&(b.ga=G.location.href);try{b.title=a.frameElement(G).id+"@"+location.href}catch(d){b.title="frame without title"}}""==b.ga&&(b.la="4: old_browser.uri_courant",b.ga=c);return b}
function Wb(a){var b=[];("callPhantom"in G||"_phantom"in G||"phantom"in G)&&b.push("phantom");("callSelenium"in G||"_selenium"in G)&&b.push("selenium");"__nightmare"in G&&b.push("nightmare");G.navigator.webdriver&&b.push("webdriver");G.document.documentElement.getAttribute("selenium")&&b.push("docselenium");Object.keys(G).some(function(c){return/^\$cdc_/.test(c)})&&b.push("cdc");Object.keys(G).some(function(c){return/^\$wdc_/.test(c)})&&b.push("wdc");G.document.documentElement.getAttribute("webdriver")&&
b.push("docwebdriver");G.document.documentElement.getAttribute("driver")&&b.push("docdriver");/Chrome/.test(G.navigator.userAgent)&&"Google Inc"==G.navigator.vendor&&!G.navigator.plugins.length&&b.push("plugins");""===G.navigator.languages&&b.push("languages");(function(c){return!(!c.getContext||c.getContext("webgl"))})(G.document.createElement("canvas"))&&b.push("webgl");0<b.length&&(a.j.headless=b.join(","));b=[];Object.getOwnPropertyDescriptor(G.navigator,"userAgent")&&b.push("ua");(function(c,
d){return c[d]instanceof Function&&!!c[d].toString().match("^function "+d+"\\(\\) \\{\\s+\\[native code\\]\\s+\\}$")})(G,"IntersectionObserver")||b.push("io");Object.getOwnPropertyDescriptor(G.document,"hidden")&&b.push("hidden");0<b.length&&(a.j.falsify=b.join(","))}
function Yb(){function a(){var d={},f={Flash:"ShockwaveFlash.ShockwaveFlash.1",PDF:"AcroPDF.PDF",Silverlight:"AgControl.AgControl",QuickTime:"QuickTime.QuickTime"};if(G.ActiveXObject){var e=function(r){try{var p=new ActiveXObject(r);try{return p.GetVariable("$version")}catch(q){try{return p.GetVersions()}catch(u){try{for(r=9;0<r;r--)if(p.isVersionSupported(r+".0"))return r}catch(x){}return!0}}}catch(q){return!1}};for(g in f){var k=e(f[g]);k&&(d[g]=k)}G.navigator.javaEnabled()&&(d.java="")}else{f.Java=
void 0;var g=G.navigator.plugins;for(e in g)for(k in f){var m=g[e].description;if(m&&-1!=m.indexOf(k)){var h=g[e].version;d[k.toLowerCase()]=h?h:g[e].name+" "+m}}}for(var n in d)f=/[0-9]+/.exec(d[n]),d[n]=f?f[0]:"";return d}var b=/^.* ([^ ]+)(.{2}) [^ ]+$/.exec(new Date);b=b?b.slice(1).join(":"):"";var c="";try{c=JSON.stringify(a())}catch(d){}return function(d){var f=0;if(!d.length)return f;for(var e=0;e<d.length;e++)f=(f<<5)-f+d.charCodeAt(e),f&=f;return f}(b+c)+function(){var d={monospace:void 0,
"sans-serif":void 0,serif:void 0},f="cursive;monospace;serif;sans-serif;fantasy;default;Arial;Arial Black;Arial Narrow;Arial Rounded MT Bold;Bookman Old Style;Bradley Hand ITC;Century;Century Gothic;Comic Sans MS;Courier;Courier New;Georgia;Gentium;Impact;King;Lucida Console;Lalit;Modena;Monotype Corsiva;Papyrus;Tahoma;TeX;Times;Times New Roman;Trebuchet MS;Verdana;Verona".split(";"),e=G.document.createElement("span");e.style.position="absolute";e.style.top=e.style.left="-1000px";e.style["font-size"]=
"72px";e.innerText="mmmmmmmmmmlli";G.document.body.appendChild(e);for(var k in d)e.style["font-family"]=k,d[k]=[e.offsetWidth,e.offsetHeight];k=f.length;a:for(;0<k--;){for(var g in d)if(e.style["font-family"]=f[k]+","+g,e.offsetWidth!=d[g][0]||e.offsetHeight!=d[g][1]){f[k]="t";continue a}f[k]="f"}G.document.body.removeChild(e);return f.join("")}()}function Vb(a){a=ub(a);a=a.protocol+"//"+a.host;var b=G.document.createElement("link");b.rel="preconnect";b.href=a;G.document.head.appendChild(b)}
function Xb(a,b){b?b.parentNode.insertBefore(a,b.nextSibling):(G.document.body||G.document.head).appendChild(a)}function Y(a){return K(a)?(a.textContent||a.innerText||"").trim():null}
l.ja=function(a,b,c){var d=c&&c["%b"]||null;if(d){var f="text/plain";c["%t"]&&(f=c["%t"],delete c["%t"]);d=new Blob([d],{type:f});delete c["%b"]}var e=this.url(a,b,c);if(e){b=function(){if(!a||a.ended||d){try{var g=new XMLHttpRequest;g.open(d?"POST":"GET",e,a?!a.ended:!0);g.send(d)}catch(m){return}return!0}};if(c=!function(){if(M(G.fetch)&&K(G.chrome)){var g={mode:"no-cors",cache:"no-cache",keepalive:!0};d&&(g.method="POST",g.body=d);G.fetch(e,g);return!0}}()){a:{if(M(G.navigator.sendBeacon))try{var k=
G.navigator.sendBeacon(e,d);break a}catch(g){}k=void 0}c=!k}c&&!b()&&((new Image).src=e)}};
l.Ga=function(a,b,c){function d(){f.ja(a,b,c);a.g=!1;a.l("fw",{state:a.g})}var f=this;c.appname=G.navigator.appName||"unknown";c.fai=this.s.title;c.iframe=this.s.Fa?this.s.da?3:1:0;c.fake=function(){return""+~~f.s.$a+~~f.s.pb+~~f.s.qb+~~f.s.G+~~f.s.rb+~~(0==G.screen.height&&0==G.screen.width||0==G.devicePixelRatio)};c.resolution=G.screen.width+"x"+G.screen.height;c.nav_lang=G.navigator.language;c.debug=this.s.la;c.url_referrer=this.s.ga.substr(0,500);c.ao=this.s.Wa;try{c.nb_cpu=G.navigator.hardwareConcurrency}catch(h){}c.data=
Yb();a.j.activetab=function(){return~~f.S};if(4==a.m.fwtype)d();else{var e=function(h){if(!N(a.g)){a.g=!1;h=db(h)?h:"";if("%%BLOCK%%"==h.trim())a.ra&&(a.g=!0);else{var n={};h=h.split("\n").map(function(q){return q.split("+").map(function(u){return u.trim()})}).filter(function(q){return q.every(function(u){return 0<u.length})}).filter(function(q){q=q.sort().join("+");if(q in n)return!1;n[q]=1;return!0});if(h.length)for(var r=function x(u){if(u){for(var t=[u],z=K(u.frames)?u.frames.length:0;0<z--;)t.push.apply(t,
v(x(u.frames[z])));return t}}(G.top).reduce(function(u,x){try{u.push.apply(u,v(x.document.querySelectorAll("title,h1,h2,h3,h4,h5,h6,p")))}catch(t){}return u},[]).reduce(function(u,x){return Y(x).split(/[^\p{L}]/u).filter(function(t){return 0<t.length}).reduce(function(t,z){t[z.toLowerCase()]=1;return t},u)},{}),p=0;p<h.length;p++)if(h[p].every(function(u){return u.toLowerCase()in r})){a.ra&&(a.g=!0);c.ads_forceblock=1;c.alerte_desc="keyword content:"+h[p].join("+");f.ja(a,b,c);break}}a.l("fw",{state:a.g})}},
k=this.url(a,b,c);if(k){var g=function(){var h=String.fromCharCode(97+26*Math.random())+Math.random().toString(16).substr(2);Object.defineProperty(G,h,{value:e.bind(f)});var n=G.document.createElement("script");n.src=k+"&jsonp="+h;n.setAttribute("data-adloox-sid",a.O);n.onerror=d.bind(f);Xb(n,S||G.document.head)};try{var m=new XMLHttpRequest;m.open("GET",k);m.onload=function(){if(4==m.readyState){if(400<=m.status)return g();e(m.responseText)}};m.onerror=g;m.ontimeout=g;m.timeout=5E3;m.send(null)}catch(h){g()}}}};
l.url=function(a,b,c){if(b=Tb.prototype.url.call(this,a,b,c))return b.split("[ADL_DOM]").join(ub(this.s.Wa||G.origin).hostname||"")};function Zb(){function a(){a=J;b.start()}X.call(this,"browser");var b=new Sb(this);this.U[b.O]=b;S&&S.setAttribute("data-adloox-sid",b.O);this.o=10;b.subscribe("start",this.F,this);"prerender"==G.document.visibilityState?G.document.addEventListener("visibilitychange",function(){a()},this.s.G?!1:{passive:!0,once:!0}):a();this.g()}qa(Zb,X);
Zb.prototype.sa=function(a,b,c){a.ra&&a.subscribe("impression",function(d){var f=d.I.v||G.document.body;"BODY"!=f.tagName||d.C.s.Fa||d.C.s.ia||(f=null);f&&(c.state?f.style.visibility="hidden":"hidden"==f.style.visibility&&d.m.targetelt.length&&(f.style.visibility="visible"));(d=d.audio.v)&&c.state&&(d.muted=!0)});X.prototype.sa.call(this,a,b,c)};
Zb.prototype.F=function(a){function b(){var g=d?c.s.da?G.top.document.documentElement:void 0:$b(c,a);g?(a.j.d6=d?"found-takeover":a.m.targetelt.length?"found-targetelt":"found-wabbit",a.l("adunit","VIDEO"==g.tagName?{video:g}:{slot:g})):null===g?(k++,a.j.d7=k,Q(b,Math.min(5E3,k*k*200))):(a.j.d6="died",a.end())}var c=this,d=1==a.m.creatype,f=S?S.parentNode:null;if(!d&&!a.m.targetelt.length&&f){var e=/ celtra-ad-v[34] /.test(" "+f.className+" ")?f:f.querySelector(".celtra-ad-v3,.celtra-ad-v4");if(e){a.j.d6=
"hunt-celtra";f=function(){var g=e.celtra.viewabilityObservee;a.j.d6="found-celtra";a.l("adunit","VIDEO"==g.tagName?{video:g}:{slot:g})};(e.celtra||{}).loaded?f():e.addEventListener("celtraLoaded",f,this.s.G?!1:{passive:!0});return}}var k=0;a.j.d3=G.screen&&G.screen.width+"x"+G.screen.height||void 0;a.j.d6=d?"hunt-takeover":a.m.targetelt.length?"hunt-targetelt":"hunt-wabbit";a.j.d7=k;a.j.d8=a.m.targetelt.length&&""+a.m.targetelt||void 0;b()};
function $b(a,b){function c(t){for(var z=[G],C=0;C<z.length;C++){var A,y=z[C];if(y){for(A=K(y.frames)?y.frames.length:0;0<A--;)-1==z.indexOf(y.frames[A])&&z.push(y.frames[A]);if(K(y.parent)&&y!=y.parent)for(A=K(y.parent.frames)?y.parent.frames.length:0;0<A--;)-1==z.indexOf(y.parent.frames[A])&&z.push(y.parent.frames[A])}}for(C=0;C<t.length;C++)for(A=0;A<z.length;A++){y=void 0;try{y=z[A].document}catch(F){}if(y&&y.body){var I=void 0;try{I=y.getElementById(t[C])}catch(F){I=null}if(I)return I;try{I=
y.body.getElementsByClassName(t[C])}catch(F){I=[]}if(I.length)return I[0];try{I=y.body.querySelector(t[C])}catch(F){I=null}if(I)return I}}return null}function d(t){function z(Fa){var la=Math.log(a.o-I+2);la*=la;if(!C)return la;var Bb=k(A);Fa=k(Fa);!Bb&&Fa?la*=.2:Bb&&!Fa&&(la*=5);return la}var C=null,A=null,y=null,I=a.o,F=t;if(F.ownerDocument.head.contains(F)){F=F.ownerDocument.body.lastChild;if(!F)return null;do F=F.previousSibling;while(F&&1!=F.nodeType)}var E=null,D=null,U=null,V=null,ma=0,na=0;
do{if(!E&&!D&&F&&"BODY"!=F.tagName){E=D=U=V=F;(F=F.parentNode)&&"BODY"==F.tagName&&(F=null);do D=D.nextSibling;while(D&&1!=D.nodeType)}if(E&&ma>=na){var ta=(U=g(E))&&z(U);!U||C&&U.width*U.height/ta<A.width*A.height/y||!f(E,U)||(C=E,y=ta,A=U);U=E;do E=E.previousSibling;while(E&&1!=E.nodeType);for(;E&&E.children&&E.children.length;)E=E.children[E.children.length-1],ma++}if(D&&na>=ma){ta=(V=g(D))&&z(V);!V||C&&V.width*V.height/ta<A.width*A.height/y||!f(D,V)||(C=D,y=ta,A=V);V=D;do D=D.nextSibling;while(D&&
1!=D.nodeType);for(;D&&D.children&&D.children.length;)D=D.children[0],na++}!E&&U&&ma>=na&&((E=U.parentNode)&&"BODY"==E.tagName&&(U=E=null),ma--);!D&&V&&na>=ma&&((D=V.parentNode)&&"BODY"==D.tagName&&(V=D=null),na--)}while((E||D||F)&&0<I--);C||250!=a.o||"complete"!==t.ownerDocument.readyState||(C=void 0);a.o=Math.min(250,2*a.o);return C}function f(t,z){if(!eb(t))return!1;switch(t.tagName){case "DIV":var C=t.style["background-image"];if(C&&!/^url\("?([^")]+)"?\)$/.test(C))break;case "SPAN":if(t.innerText&&
t.innerText.trim())break;case "ARTICLE":case "VIDEO":case "IMG":case "CANVAS":case "OBJECT":case "EMBED":case "SVG":case "IFRAME":case "INS":return"proxy"!=t.getAttribute("data-adloox-type")&&e(t,z)}return!1}function e(t,z){if(t.clientWidth+5<t.scrollWidth)return!1;z=z||a.va(t);if(20>z.width||20>z.height)return!1;t=Ib(W(t));return 0<=z.top+t.y+5&&0<=z.left+t.x+5}function k(t){return!!{"390x220":1,"320x240":1,"320x250":1,"320x300":1,"600x400":1,"330x280":1,"320x100":1,"970x250":1,"320x50":1,"120x20":1,
"160x20":1,"210x30":1,"300x600":1,"300x1050":1,"970x90":1,"300x250":1,"180x150":1,"160x600":1,"720x90":1,"970x60":1,"120x60":1,"80x30":1,"600x250":1,"600x150":1,"600x600":1,"720x310":1,"550x480":1}[t.width+"x"+t.height]}function g(t){if(t=a.va(t))t.width=10*(t.width/10|0),t.height=10*(t.height/10|0);return t}var m=S||G.document.body;try{if(b.m.targetelt.length)return c(b.m.targetelt);var h=m;try{for(;!e(h)&&W(h)!=G.top;){h=a.frameElement(h);if(!h)break;m=h}}catch(t){}h=null;h=d(m);var n=a.frameElement(m);
!h&&n&&(h=d(n));if(!h&&(W(m)!=G.top||b.C.s.ia)){var r=m.ownerDocument.body;r&&e(r)&&(h=r)}if(!h&&n&&(W(n)!=G.top||b.C.s.ia)){var p=n.ownerDocument.body;p&&e(p)&&(h=p)}if(h)for(var q=g(h);;){var u=h.parentNode;if(!u||!f(u))break;var x=g(u);if(!x||q.width!=x.width||q.height!=x.height)break;h=u}return h}catch(t){b.l("error",{err:t.message,"%b":t.stack}),b.j.d2=t.message}}
function ac(){function a(){K(G.mraid)&&M(G.mraid.getState)?"loading"==G.mraid.getState()?G.mraid.addEventListener("ready",b):b():a.t=Q(a,200)}function b(){c.l("MRAID.ready");c.N.mraid={version:G.mraid.getVersion(),type:G.mraid.getPlacementType(),env:G.MRAID_ENV};var d=G.mraid.getScreenSize();c.j.resolution=d.width+"x"+d.height;c.I.data({id:"mraid",Z:!1});Q(c.start,0)}X.call(this,"mraid");this.o=this.F=null;var c=new Sb(this);this.U[c.O]=c;c.m.creatype=2;S&&S.setAttribute("data-adloox-sid",c.O);c.subscribe("start",
this.xa,this);a();this.g()}qa(ac,X);ac.prototype.sa=function(a,b,c){if(c.state)try{G.mraid.close(),G.mraid.close(),G.mraid.unload()}catch(d){}X.prototype.sa.call(this,a,b,c)};
ac.prototype.xa=function(a){var b=this;this.F="hidden"==G.mraid.getState();G.mraid.addEventListener("stateChange",function(c){a.l("MRAID.stateChange",c);b.F="hidden"==c;b.F&&a.l("send.visi");bc(b,a)});3<=a.N.mraid.version?G.mraid.addEventListener("exposureChange",function(c){a.l("MRAID.exposureChange",c);b.o=c/100;bc(b,a)}):(this.o=~~G.mraid.isViewable(),G.mraid.addEventListener("viewableChange",function(c){a.l("MRAID.viewableChange",c);b.o=~~c;bc(b,a)}));bc(this,a);a.l("adunit",{slot:G.document.documentElement})};
function bc(a,b){b.I.data({id:"mraid",state:a.F,ratio:a.o})}
function cc(){X.call(this,"vpaid");var a=this;this.H=null;this.ka=[];this.Ma=[];this.Ya=this.ua=this.Ca=this.Qa=this.height=this.width=this.K=this.slot=this.D=null;this.version=2;this.Na=Infinity;this.qa=this.Va=null;this.Oa=this.skippable=!1;this.volume=null;this.F=0;this.M=function(d){(a.D==a.$?a.H.l:J)(d)};this.Ea=[[.01,function(){return a.M("VPAID.AdVideoStart")}],[.25,function(){return a.M("VPAID.AdVideoFirstQuartile")}],[.5,function(){return a.M("VPAID.AdVideoMidpoint")}],[.75,function(){return a.M("VPAID.AdVideoThirdQuartile")}],
[.99,function(){return a.M("VPAID.AdVideoComplete")}]];this.Oa=!1;this.$={resizeAd:function(d,f,e){this.width=d;this.height=f;this.Qa=e;this.H.l("geometry")},startAd:function(){this.$.startAd=J;this.K.play()},stopAd:function(){this.$.stopAd=J;this.H.end()},pauseAd:function(){this.K.pause()},resumeAd:function(){this.K.play()},expandAd:J,collapseAd:J,skipAd:function(){this.skippable&&(this.$.skipAd=J,this.Oa=!0,this.D.stopAd.call(this.D))},getAdLinear:function(){return!0},getAdWidth:function(){return this.width},
getAdHeight:function(){return this.height},getAdExpanded:function(){return!1},getAdSkippableState:function(){return this.skippable},getAdRemainingTime:function(){return isFinite(this.K.duration)?this.K.duration-this.K.currentTime:-2},getAdDuration:function(){return isFinite(this.K.duration)?this.K.duration:-2},getAdVolume:function(){return isFinite(this.K.volume)?this.K.volume:1},setAdVolume:function(d){L(d)&&0<=d&&1>=d&&(this.K.volume=d)},getAdCompanions:function(){return this.Va},getAdIcons:function(){return!1}};
for(var b in this.$)this.$[b]=this.$[b].bind(this);this.o={handshakeVersion:function(d){d=O(d);1<=d&&2>=d&&(this.version=d);return this.version+".0"},initAd:function(d,f,e,k,g,m){function h(){n.qa&&p.l("VPAID.AdClickThru",Y(n.qa),n.qa.id,!0)}var n=this,r=(((g||{}).AdParameters||"").match(/(?:^|.*&)vpaid=adloox(?:$|&.*)/)||[""])[0],p=new Sb(this,r);p.m.creatype=23;this.H=this.U[p.O]=p;S&&S.setAttribute("data-adloox-sid",p.O);r&&("adparameters"in p.m?g.AdParameters=p.m.adparameters:delete g.AdParameters);
this.width=d;this.height=f;this.Qa=e;this.Ca=k;this.ua=g;this.Ya=m;this.slot=m.slot;this.K=m.videoSlot;p.N.vpaid={videoSlotCanAutoPlay:m.videoSlotCanAutoPlay,videoSlotIsAProxy:!eb(this.K)};p.audio.data({id:"vpaid",Z:!1});p.subscribe("VPAID.AdStarted",function(){n.volume=dc(n)});for(d=this.ka.length;0<d--;)f=this.ka[d],p.subscribe(f.name,f.pa,f.context);p.start();p.subscribe("fw",function(q,u,x){x.state&&n.W("adloox.com brand safety")});p.subscribe("adunit",function(q,u,x){function t(A,y){x.video.addEventListener(A,
y,n.s.G?!1:{passive:!0});z.push([A,y])}var z=[];q.subscribe("end",function(){z.forEach(function(A){x.video.removeEventListener(A[0],A[1])})});t("loadedmetadata",function(){n.M("VPAID.AdLoaded");n.M("VPAID.AdDurationChange");t("durationchange",function(){n.M("VPAID.AdDurationChange")})});var C=!1;t("play",function(){C||(C=!0,n.M("VPAID.AdStarted"))});t("timeupdate",function(){2>n.version&&n.M("VPAID.AdRemainingTimeChange");!n.skippable&&x.video.currentTime>=n.Na&&(n.skippable=!0,n.M("VPAID.AdSkippableStateChange"));
var A=isFinite(x.video.duration)&&0<x.video.duration&&x.video.currentTime/x.video.duration;n.Ea=n.Ea.filter(function(y){var I=L(y[0])?y[0]:Date.parse("1970-01-01 "+y[0]+"Z")/1E3/x.video.duration;if(A<I)return!0;y[1]();return!1})});t("playing",function(){C||(C=!0,n.M("VPAID.AdStarted"));q.l("rollstate.run");n.M("VPAID.AdPlaying")});t("pause",function(){x.video.ended||(q.l("rollstate.pause"),n.M("VPAID.AdPaused"))});t("volumechange",function(){dc(n)});t("ended",function(){n.D.stopAd.call(n.D)});t("error",
function(){n.W(x.video.error?x.video.error.message:"unable to load video")})});this.slot.addEventListener("click",h,this.s.G?!1:{passive:!0});p.subscribe("end",function(q){n.slot.removeEventListener("click",h);n.D==n.$&&(delete n.K.src,delete n.K.preload,q.l(n.Oa&&2<=n.version?"VPAID.AdSkipped":"VPAID.AdStopped"))});d=p.m.vast;"::"==d.substr(0,2)?(p.m.vast_clickthru&&(this.qa=document.createElement("p"),this.qa.textContent=p.m.vast_clickthru),d=ec(this,p,d.substr(2))):d=":"==d.substr(0,1)?fc(this,
p,d.substr(1)):gc(this,p,d);if(!d)return this.W("unsuitable vast parameter")},startAd:function(){var d=this;2!=this.H.m.fwtype&&4!=this.H.m.fwtype?this.H.subscribe("fw",function(f,e,k){k.state||d.D.startAd.call(d.D)}):this.D.startAd.call(this.D)},subscribe:function(d,f,e){function k(g,m,h){for(var n=[],r=2;r<arguments.length;++r)n[r-2]=arguments[r];d.apply(null,v(n))}k.Za=d;this.H?this.H.subscribe("VPAID."+f,k,e):(-1==this.Ma.indexOf(f)&&this.Ma.push(f),this.ka.unshift({name:"VPAID."+f,pa:k,context:e||
this}))},unsubscribe:function(d,f){if(this.H)this.H.unsubscribe("VPAID."+f,d);else for(var e=this.ka.length;0<e--;)this.ka[e].name=="VPAID."+f&&this.ka[e].pa.Za==d&&this.ka.splice(e,1)},resizeAd:J,stopAd:J,pauseAd:J,resumeAd:J,expandAd:J,collapseAd:J,skipAd:J,getAdLinear:J,getAdWidth:J,getAdHeight:J,getAdExpanded:J,getAdSkippableState:J,getAdRemainingTime:J,getAdDuration:J,getAdVolume:J,setAdVolume:J,getAdCompanions:J,getAdIcons:J};b={};for(var c in this.o)b.ha=c,this.o[b.ha]=this.o[b.ha]==J?function(d,
f){for(var e=[],k=1;k<arguments.length;++k)e[k-1]=arguments[k];if(this.D)try{var g=this.D[d].apply(this.D,e);J.apply(null,["VPAID",d].concat(v(e),["=>",g]));return g}catch(m){}else J.apply(null,["VPAID (noop)",d].concat(v(e)))}.bind(this,b.ha):function(d){return function(f,e){for(var k=[],g=1;g<arguments.length;++g)k[g-1]=arguments[g];J.apply(null,["VPAID (wrapper)",d.ha].concat(v(k)));return f.apply(this,k)}}(b).bind(this,this.o[b.ha]),b={ha:b.ha};this.xa=function(){return this.o}.bind(this);this.g()}
qa(cc,X);function ec(a,b,c){b.l("adunit",{slot:a.slot,video:a.K});a.D=a.$;dc(a);b.subscribe("impression",function(d){d.l("VPAID.AdImpression")});a.K.preload="metadata";a.K.src=a.url(b,db(c)?c:Y(c));a.K.load();return!0}function dc(a){var b=a.D.getAdVolume.call(a.D);0<a.volume&&0==b?a.M("VPAID.AdVolumeChange.mute"):0==a.volume&&0<b&&a.M("VPAID.AdVolumeChange.unmute");a.volume=b;a.M("VPAID.AdVolumeChange");a.H.audio.data({id:"vpaid",ratio:a.volume,muted:0==a.volume});return b}
function hc(a,b,c,d,f,e){for(var k=G.navigator.connection?1E3*G.navigator.connection.downlink:5E4,g=[],m=0;m<c.length;m++){var h=c[m];if(!h.getAttribute("apiFramework")){var n=h.getAttribute("type");if(n){var r=h.getAttribute("codec");r&&(n+=';codecs="'+r+'"');if(a.K.canPlayType(n)){var p=h.getAttribute("width"),q=h.getAttribute("height");p&&q&&(n="true"==(h.getAttribute("scalable")||"false").toLowerCase(),r="true"==(h.getAttribute("maintainAspectRatio")||"true").toLowerCase(),(d||n||p==a.width&&
q==a.height)&&!(!f&&n&&1<p*q/(a.width*a.height))&&(p=a.width/p/(a.height/q),f||!n||!r||.95<=p&&1.05>=p))&&(n=Math.max(h.getAttribute("bitrate"),h.getAttribute("maxBitrate")),k<n||!e&&0<a.Ca&&n>a.Ca||g.push(h))}}}}g=g.sort(function(u,x){u=Math.max(u.getAttribute("bitrate"),u.getAttribute("maxBitrate"));x=Math.max(x.getAttribute("bitrate"),x.getAttribute("maxBitrate"));return e?u-x:x-u});k=g[0];for(m=1;m<g.length;m++)h=k.getAttribute("width"),n=k.getAttribute("height"),r=g[m].getAttribute("width"),
p=g[m].getAttribute("height"),1-Math.abs(r*p/(a.width*a.height))<1-Math.abs(h*n/(a.width*a.height))&&(k=g[m]);return k?ec(a,b,k):d&&f&&e?!1:hc(a,b,c,!0,!!d,!!f)}
function fc(a,b,c,d){d&&(a.ua=d.querySelector("AdParameters"),a.ua={AdParameters:Y(a.ua)||void 0});var f=document.createElement("iframe");f.src="javascript:false";f.style.display="none";f.onload=function(){var e=document.createElement("script");e.src=a.url(b,c);e.onload=function(){var k=f.contentWindow.getVPAIDAd;if(!M(k))return a.W("VPAID unit has no getVPAIDAd");a.D=k();b.subscribe("VPAID.AdSkipped",b.end);b.subscribe("VPAID.AdStopped",b.end);b.subscribe("VPAID.AdVideoFirstQuartile",function(){b.l("send.visi")});
b.subscribe("VPAID.AdVideoMidpoint",function(){b.l("send.visi")});b.subscribe("VPAID.AdVideoThirdQuartile",function(){b.l("send.visi")});b.subscribe("VPAID.AdVideoComplete",function(){b.l("send.visi")});var g=!1,m=!1,h=null;b.subscribe("VPAID.AdVideoThirdQuartile",function(n){h=lb(function(){m=2>a.D.getAdRemainingTime.call(a.D)},500);n.subscribe("VPAID.AdVideoComplete",function(r){kb(h);m=!1;g&&r.l("VPAID.AdStopped")})});a.Ma.forEach(function(n){"AdStopped"==n?a.D.subscribe.call(a.D,function(){g=
!0;m||(h&&kb(h),b.l("VPAID.AdStopped"))},n,a):a.D.subscribe.call(a.D,b.l.bind(a,"VPAID."+n),n,a)});b.subscribe("VPAID.AdLoaded",function(n){var r=a.K;try{if(!r.src){var p=a.slot.querySelector("iframe"),q=(p?p.contentWindow:G).document.querySelector('video:not([src=""])');q&&(r=q,n.N.vpaid.videoSlotQuirk=!0)}}catch(u){}n.l("adunit",{slot:a.slot,video:r})});a.D.initAd.call(a.D,a.width,a.height,a.Qa,a.Ca,a.ua,a.Ya)};f.contentWindow.document.head.appendChild(e)};Xb(f,S);return!0}
function ic(a,b,c,d){if(d=d&&d.getAttribute("skipoffset"))a.Na=Date.parse("1970-01-01 "+d+"Z")/1E3,b.N.vpaid.skipoffset=a.Na;(b=c.querySelector("ClickThrough"))&&/^https?:/.test(Y(b))&&(a.qa=b)}
function jc(a,b,c,d){var f={skip:"AdSkipped",creativeView:"AdStarted",start:"AdVideoStart",firstQuartile:"AdVideoFirstQuartile",midpoint:"AdVideoMidpoint",thirdQuartile:"AdVideoThirdQuartile",complete:"AdVideoComplete",pause:"AdPaused",resume:"AdPlaying",Impression:"AdImpression",ClickTracking:"AdClickThru",Error:"AdError",mute:"AdVolumeChange.mute",unmute:"AdVolumeChange.unmute"};[].concat(v(c.querySelectorAll("Tracking,Impression,ClickTracking,Error,Viewable,NotViewable,ViewUndetermined"))).forEach(function(g){var m=
Y(g);if(/^https?:/.test(m)){var h=function(){b.l("send",a.url(b,m))},n=g.getAttribute("event")||g.tagName;switch(n){case "progress":d&&(g=(g.getAttribute("offset")||"").trim(),"%"==g.substr(-1)?a.Ea.push([O(g.substr(0,g.length-1))/100,h]):/^[0-9:]+$/.test(g)&&a.Ea.push([g,h]));break;case "Viewable":b.Ba("px_view",Y(g));break;case "NotViewable":b.Ba("px_viewn",Y(g));break;case "ViewUndetermined":b.Ba("px_viewu",Y(g));break;default:(g=f[n])&&b.subscribe("VPAID."+g,h)}}});c=c.querySelectorAll("Survey");
for(var e=0;e<c.length;e++){var k=Y(c[e]);/^https?:/.test(k)&&b.Ba("js_imp",k)}}
function gc(a,b,c,d){var f=new XMLHttpRequest;f.open("GET",a.url(b,c));f.withCredentials=!d;f.onload=function(){if(4==f.readyState){if(400<=f.status)return a.W.call(a,"failed to fetch VAST");a:{var e=f.responseXML;if("VAST"!=e.documentElement.tagName)var k=a.W("not a VAST tag");else{k=!a.F&&b.m.vast_skiptracking;var g=[],m=[];e=e.querySelectorAll("Ad");for(var h=0;h<e.length;h++){var n=e[h],r=n.getAttribute("sequence");r?(r=O(r),0<r&&(g[r]=n)):m.push(n)}g=g.concat(m);for(m=0;m<g.length;m++)if(e=g[m]){if(h=
e.querySelector("VASTAdTagURI")){ic(a,b,e);k||jc(a,b,e);k=5>a.F++?gc(a,b,Y(h)):a.W("too many wrappers");break a}a.Va=(e.querySelector("CompanionAds")||{}).outerHTML;h=e.querySelector("Creatives").querySelectorAll("Creative");for(n=0;n<h.length;n++)if(r=e.querySelector("Linear")){ic(a,b,e,r);k||jc(a,b,e,r);var p=r.querySelectorAll("MediaFiles > MediaFile"),q=r.querySelector("MediaFiles > MediaFile[apiFramework='VPAID'][type='application/javascript']");if(q&&fc(a,b,Y(q),r)||hc(a,b,p)){k=!0;break a}}}k=
!1}}if(!k)return a.W.call(a,"VAST returned nothing usable")}};f.onerror=function(){if(d)return a.W.call(a,"unable to download VAST");gc(a,b,c,!0)};f.ontimeout=a.W.bind(a,"timeout downloading VAST");f.timeout=5E3;f.send(null);return!0}cc.prototype.W=function(a){this.H.l("VPAID.AdError",a);this.H.end()};
function kc(){Tb.call(this,"omid");var a=this;Ta(function(b){switch(b.type){case "sessionStart":var c=new Sb(a,b.data.verificationParameters);c.m.creatype=0;a.U[b.adSessionId]=c;c.data={context:b.data.context};S&&S.setAttribute("data-adloox-sid",c.O);a.Ua(b);default:try{a.Ta(b)}catch(d){a.U[b.adSessionId].l("error",{err:"omid: "+d.message,"%b":d.stack})}}});this.g()}qa(kc,Tb);l=kc.prototype;
l.Ta=function(a){var b=this.U[a.adSessionId],c=a.data,d=b.data.context;b.l("OMID."+a.type,a);switch(a.type){case "sessionStart":var f=function(k){return db(k)&&!k.length?void 0:k};b.N.omid={};["impressionType","creativeType","mediaType","pageUrl","contentUrl"].forEach(function(k){return b.N.omid[k]=f(c[k])});"apiVersion environment accessMode adSessionType omidNativeInfo omidJSInfo app deviceInfo".split(" ").forEach(function(k){return b.N.omid[k]=f(d[k])});"app"==d.environment&&(b.j.appname=d.app.appId);
b.I.data({id:"omid",Z:!1});b.audio.data({id:"omid",Z:!1});break;case "sessionError":b.l("error",{err:"omid","%b":a.data.message});break;case "sessionFinish":b.end();break;case "loaded":switch(c.creativeType){case "audio":case "video":b.m.creatype=6;break;default:b.m.creatype=2}b.N.omid.autoPlay=a.data.autoPlay;b.N.omid.skipOffset=a.data.skipOffset;b.N.omid.position=a.data.position;b.N.omid.duration=a.data.duration;break;case "impression":if(!b.m.creatype)switch(c.mediaType){case "video":b.m.creatype=
6;break;default:b.m.creatype=2}6!=b.m.creatype||b.data.audio||b.audio.data({id:"omid",T:!0,ratio:1});case "geometryChange":this.Ha(b,a);K(c.adView)&&(b.l("geometry",{width:c.adView.geometry.width,height:c.adView.geometry.height,top:c.adView.geometry.y,left:c.adView.geometry.x}),b.I.data({id:"omid",T:!0,ratio:c.adView.percentageInView/100}));break;case "start":this.Ha(b,a);case "volumeChange":var e=function(k){k=Math.max(0,Math.min(1,k));return isNaN(k)?1:k};b.audio.data({id:"omid",T:!0,ratio:e(a.data.mediaPlayerVolume)*
e(a.data.videoPlayerVolume)*e(a.data.deviceVolume)});b.data.audio=!0;break;case "resume":b.l("rollstate.run");break;case "pause":b.l("rollstate.pause")}};
l.Ha=function(a,b){this.Ha=J;b=b.data;var c={};switch(b.creativeType){case "audio":break;default:var d;(d=!K(b.adView)||-1!=b.adView.reasons.indexOf("notFound"))||(d=b.viewport,d=!(K(d)&&0<d.width*d.height));if(d)return;c.slot=a.data.context.slotElement;c.video=a.data.context.videoElement;b.adView&&(c.rect=b.adView.geometry);"limited"==a.data.context.accessMode&&(a.j.resolution=b.viewport.width+"x"+b.viewport.height)}a.start();a.l("adunit",c)};
l.Ua=function(a){function b(k){return c(k)}function c(k){for(var g=f.length;0<g--;){var m=f[g][0].timestamp;if(m==k.timestamp){f[g].unshift(k);return}if(m>k.timestamp)break}f.splice(g+1,0,[k])}var d=this;this.Ua=J;R(null,"impression",function(k){(k.m.js_imp||[]).forEach(function(g){Wa(this.url(k,g))})});var f=[],e=a.data.context;-1!=e.supports.indexOf("vlid")&&B.addEventListener(a.data.creativeType?"media":"video",b);"limited"!=e.accessMode&&-1==e.supports.indexOf("clid")||B.addEventListener("geometryChange",
b);B.addEventListener("impression",b);Q(function(){c=d.Ta.bind(d);f=f.reduce(function(g,m){return g.concat(m)},[]);for(var k=f.length;0<k--;)c(f[k])},0)};l.ja=function(a,b,c){c&&c["%b"]&&(c.body=c["%b"],delete c["%b"]);(a=this.url(a,b,c))&&Ua(a)};l.Ga=function(a,b,c){var d=this,f=this.url(a,b,c);if(f){var e=function(){a.l("fw",{state:!1});d.ja(a,b,c)};a.ra?Wa(f,function(){},e):e()}};
l.url=function(a,b,c){if(b=Tb.prototype.url.call(this,a,b,c))return b.split("[ADL_DOM]").join(ub(a.N.omid.pageUrl||a.N.omid.contentUrl||"").hostname||"")};var Z=null;function lc(){delete G.getVPAIDAd;Z=J;Z=new cc;return Z.xa()}function mc(){G.getVPAIDAd==lc&&delete G.getVPAIDAd;Z||(K(G.MRAID_ENV)||K(G.mraid)?(Z=J,Z=new ac):(Z=J,Z=new Zb))}function nc(){Q(function(){Q(mc,0)},0)}if(B)try{Z=new kc}catch(a){}
Z||(H?(M(G.getVPAIDAd)||(G.getVPAIDAd=lc),"loading"===G.document.readyState?G.document.addEventListener("DOMContentLoaded",nc,!1):nc()):Z=new Tb);}).call(this);
//# sourceMappingURL=tfav_adl_55.js.map
